{{- if .Values.providers.file.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefik.fullname" . }}-file-provider
  namespace: traefik
  labels:
  {{- include "traefik.labels" . | nindent 4 }}
data:
  config.yml:
    {{ toYaml .Values.providers.file.content | nindent 4 }}
{{- end -}}
