{{- range $name, $config := .Values.tlsStore }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: {{ $name }}
  namespace: traefik
  labels:
    {{- include "traefik.labels" $ | nindent 4 }}
spec:
  {{- toYaml $config | nindent 2 }}
---
{{- end -}}
